version: 1  
disable_existing_loggers: false  
handlers:  
  console:  
    class: logging.StreamHandler  
    level: DEBUG
    formatter: standard  
    stream: ext://sys.stdout  
formatters:  
  standard:  
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  
root:  
  level: WARNING
  handlers: [console]  
loggers:

  __main__:
    level: DEBUG
    handlers: [ console ]
    propagate: false
